# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fakultas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fokus_Penelitian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=100)),
                ('minor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Penelitian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_penelitian', models.CharField(max_length=500)),
                ('nomor_kontrak', models.CharField(max_length=100)),
                ('tahun_pelaksanaan', models.PositiveSmallIntegerField()),
                ('jenis_penelitian', models.CharField(max_length=50)),
                ('asal_sumber_dana', models.CharField(max_length=50)),
                ('jenis_sumber_dana', models.CharField(max_length=50)),
                ('nama_sumber_dana', models.CharField(max_length=100)),
                ('institusi_sumber_dana', models.CharField(max_length=100)),
                ('nama_institusi_sumber_dana', models.CharField(max_length=100)),
                ('jumlah_dana_dalam_negeri', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jumlah_dana_luar_negeri', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status_data', models.CharField(max_length=100)),
                ('penginput', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('bidang_penelitian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.Fokus_Penelitian')),
            ],
        ),
        migrations.CreateModel(
            name='Program_Studi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_studi', models.CharField(max_length=100)),
                ('nama_fakultas', models.ForeignKey(default=b'SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='percobaan.Fakultas')),
            ],
        ),
        migrations.AddField(
            model_name='penelitian',
            name='program_studi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.Program_Studi'),
        ),
    ]
