# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('percobaan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penelitian_authors_role',
            name='tahun_pelaksanaan',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='penelitian_authors_role',
            name='penelitian',
            field=models.CharField(max_length=500),
        ),
    ]
