# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('percobaan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penelitian_authors_role',
            name='penelitian',
        ),
        migrations.AddField(
            model_name='penelitian_authors_role',
            name='judul_penelitian',
            field=models.ForeignKey(default='judul', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='percobaan.Penelitian'),
        ),
    ]
