# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('percobaan', '0002_auto_20170615_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penelitian',
            name='tahun_pelaksanaan',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
