# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('percobaan', '0002_auto_20170615_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penelitian_authors_role',
            name='tahun_pelaksanaan',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='percobaan.Penelitian'),
        ),
    ]
