# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import isbn_field.fields
import isbn_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('percobaan', '0007_auto_20170619_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Authors_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.Authors', to_field=b'authors')),
            ],
            options={
                'verbose_name_plural': 'Author Role',
            },
        ),
        migrations.CreateModel(
            name='Buku_Teks_Ajar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_buku', models.CharField(max_length=500)),
                ('tahun_terbit', models.PositiveSmallIntegerField()),
                ('isbn', isbn_field.fields.ISBNField(max_length=13, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN')),
                ('jumlah_halaman', models.PositiveSmallIntegerField()),
                ('penerbit', models.CharField(max_length=100)),
                ('pusat_riset', models.CharField(max_length=100)),
                ('status_data', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('hibah_terkait', models.ForeignKey(default=b'judul', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='percobaan.Penelitian')),
                ('penginput', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.User')),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.Program_Studi')),
            ],
            options={
                'verbose_name_plural': 'buku',
            },
        ),
        migrations.CreateModel(
            name='Forum_Authors_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.Authors', to_field=b'authors')),
            ],
            options={
                'verbose_name_plural': 'Author Role',
            },
        ),
        migrations.CreateModel(
            name='Forum_Ilmiah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kegiatan', models.CharField(max_length=500)),
                ('abstrak', models.TextField(max_length=9999)),
                ('tingkat_forum', models.CharField(choices=[(b'I', b'Internasional'), (b'N', b'Nasional')], max_length=1)),
                ('tahun_pelaksanaan', models.PositiveSmallIntegerField()),
                ('penyelenggara', models.CharField(max_length=100)),
                ('unit_penyelenggara', models.CharField(max_length=100)),
                ('mitra_sponsor', models.CharField(max_length=100)),
                ('tanggal_pelaksanaan', models.DateField(auto_now=True)),
                ('tempat_pelaksanaan', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('nama_sumber_dana', models.CharField(max_length=100)),
                ('pusat_riset', models.CharField(max_length=100)),
                ('status_data', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('hibah_terkait', models.ForeignKey(default=b'judul', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='percobaan.Penelitian')),
                ('penginput', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.User')),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.Program_Studi')),
            ],
            options={
                'verbose_name_plural': 'Forum',
            },
        ),
        migrations.CreateModel(
            name='Hak_Kekayaan_Intelektual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_HKI', models.CharField(max_length=500)),
                ('tahun_pengajuan', models.PositiveSmallIntegerField()),
                ('jenis', models.CharField(choices=[(b'H', b'Hak Cipta'), (b'M', b'Model'), (b'D', b'Desain')], max_length=1)),
                ('status', models.CharField(choices=[(b'T', b'Terdaftar'), (b'G', b'Granted')], max_length=1)),
                ('nomor_pendaftaran', models.CharField(max_length=20)),
                ('nomor_hki', models.PositiveSmallIntegerField()),
                ('pusat_riset', models.CharField(max_length=100)),
                ('status_data', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('hibah_terkait', models.ForeignKey(default=b'judul', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='percobaan.Penelitian')),
                ('penginput', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.User')),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.Program_Studi')),
            ],
            options={
                'verbose_name_plural': 'luaran',
            },
        ),
        migrations.CreateModel(
            name='Hibah_Non_Penelitian_Authors_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_buku', models.CharField(max_length=300)),
                ('penerbit', models.CharField(max_length=100)),
                ('isbn', isbn_field.fields.ISBNField(max_length=13, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN')),
            ],
            options={
                'verbose_name_plural': 'Author Role',
            },
        ),
        migrations.CreateModel(
            name='Hibah_Non_Penelitian_Kontrak_Kerja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kegiatan', models.CharField(max_length=500)),
                ('nomor_kontrak', models.CharField(max_length=500)),
                ('tahun_penelitian', models.PositiveSmallIntegerField()),
                ('jenis', models.CharField(choices=[(b'L', b'lain-lain'), (b'P', b'penulisan buku')], max_length=1)),
                ('tanggal_mulai', models.DateField(auto_now=True)),
                ('tanggal_selesai', models.DateField(auto_now=True)),
                ('unit_penyelenggara', models.CharField(max_length=100)),
                ('nilai_kontrak_penghibahan', models.FloatField(blank=True, default=None, null=True)),
                ('sumber_dana', models.CharField(max_length=100)),
                ('pusat_riset', models.CharField(max_length=100)),
                ('status_data', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('hibah_terkait', models.ForeignKey(default=b'judul', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='percobaan.Penelitian')),
                ('penginput', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.User')),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.Program_Studi')),
            ],
            options={
                'verbose_name_plural': 'hibah_non_penelitian',
            },
        ),
        migrations.CreateModel(
            name='hibah_Pengmas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kegiatan', models.CharField(max_length=500)),
                ('mitra_institusi', models.CharField(max_length=100)),
                ('nomor_kontrak', models.CharField(max_length=500)),
                ('tahun_penelitian', models.PositiveSmallIntegerField()),
                ('jumlah_dosen', models.PositiveSmallIntegerField()),
                ('jumlah_mahasiswa', models.PositiveSmallIntegerField()),
                ('tahun_pelaksanaan', models.PositiveSmallIntegerField()),
                ('lokasi_kegiatan', models.CharField(max_length=100)),
                ('nilai_kontrak_penghibahan', models.FloatField(blank=True, default=None, null=True)),
                ('sumber_dana', models.CharField(max_length=100)),
                ('pusat_riset', models.CharField(max_length=100)),
                ('status_data', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('hibah_terkait', models.ForeignKey(default=b'judul', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='percobaan.Penelitian')),
                ('penginput', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.User')),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.Program_Studi')),
            ],
            options={
                'verbose_name_plural': 'hibah_non_penelitian',
            },
        ),
        migrations.CreateModel(
            name='Hibah_Pengmas_Authors_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.Authors', to_field=b'authors')),
                ('nama_kegiatan', models.ForeignKey(default=b'hibah_pengmas', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='percobaan.hibah_Pengmas')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.Role')),
            ],
            options={
                'verbose_name_plural': 'Author Role',
            },
        ),
        migrations.CreateModel(
            name='HKI_Authors_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.Authors', to_field=b'authors')),
                ('judul_HKI', models.ForeignKey(default=b'HKI', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='percobaan.Hak_Kekayaan_Intelektual')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.Role')),
            ],
            options={
                'verbose_name_plural': 'Author Role',
            },
        ),
        migrations.CreateModel(
            name='Jurnal_Authors_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.Authors', to_field=b'authors')),
            ],
            options={
                'verbose_name_plural': 'Author Role',
            },
        ),
        migrations.CreateModel(
            name='Jurnal_Ilmiah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_jurnal', models.CharField(max_length=500)),
                ('nama_jurnal', models.CharField(max_length=500)),
                ('abstrak', models.TextField(max_length=9999)),
                ('tingkat_jurnal', models.CharField(choices=[(b'I', b'Internasional'), (b'N', b'Nasional')], max_length=1)),
                ('impact_factor', models.FloatField(blank=True, default=None, null=True)),
                ('issn', models.TextField(max_length=9)),
                ('volume', models.PositiveSmallIntegerField()),
                ('nomor', models.PositiveSmallIntegerField()),
                ('page', models.CharField(max_length=500)),
                ('issue', models.PositiveSmallIntegerField()),
                ('link', models.URLField()),
                ('pusat_riset', models.CharField(max_length=100)),
                ('status_data', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('hibah_terkait', models.ForeignKey(default=b'judul', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='percobaan.Penelitian')),
                ('penginput', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.User')),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.Program_Studi')),
            ],
            options={
                'verbose_name_plural': 'Forum',
            },
        ),
        migrations.CreateModel(
            name='Luaran_Authors_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.Authors', to_field=b'authors')),
            ],
            options={
                'verbose_name_plural': 'Author Role',
            },
        ),
        migrations.CreateModel(
            name='Luaran_Lain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_luaran', models.CharField(max_length=500)),
                ('tahun_publikasi', models.PositiveSmallIntegerField()),
                ('jenis', models.CharField(choices=[(b'P', b'Prototipe'), (b'M', b'Model'), (b'D', b'Desain')], max_length=1)),
                ('deskripsi_singkat', models.CharField(max_length=300)),
                ('penerbit', models.CharField(max_length=100)),
                ('pusat_riset', models.CharField(max_length=100)),
                ('status_data', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('hibah_terkait', models.ForeignKey(default=b'judul', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='percobaan.Penelitian')),
                ('penginput', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.User')),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.Program_Studi')),
            ],
            options={
                'verbose_name_plural': 'luaran',
            },
        ),
        migrations.CreateModel(
            name='Makalah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_makalah', models.CharField(max_length=500)),
                ('abstrak', models.TextField(max_length=9999)),
                ('tingkat_forum', models.CharField(choices=[(b'I', b'Internasional'), (b'N', b'Nasional')], max_length=1)),
                ('tahun_pelaksanaan', models.PositiveSmallIntegerField()),
                ('forum_penyelenggara', models.CharField(max_length=100)),
                ('institusi_penyelenggara', models.CharField(max_length=100)),
                ('tanggal_mulai', models.DateField(auto_now=True)),
                ('tanggal_selesai', models.DateField(auto_now=True)),
                ('tempat_pelaksanaan', models.CharField(max_length=100)),
                ('status_pemakalahan', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('nama_sumber_dana', models.CharField(max_length=100)),
                ('pusat_riset', models.CharField(max_length=100)),
                ('status_data', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('hibah_terkait', models.ForeignKey(default=b'judul', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='percobaan.Penelitian')),
                ('penginput', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.User')),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.Program_Studi')),
            ],
            options={
                'verbose_name_plural': 'Makalah',
            },
        ),
        migrations.CreateModel(
            name='Makalah_Authors_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.Authors', to_field=b'authors')),
                ('judul_makalah', models.ForeignKey(default=b'judul', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='percobaan.Makalah')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.Role')),
            ],
            options={
                'verbose_name_plural': 'Author Role',
            },
        ),
        migrations.AddField(
            model_name='luaran_authors_role',
            name='judul_luaran',
            field=models.ForeignKey(default=b'luaran', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='percobaan.Luaran_Lain'),
        ),
        migrations.AddField(
            model_name='luaran_authors_role',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.Role'),
        ),
        migrations.AddField(
            model_name='jurnal_authors_role',
            name='judul_jurnal',
            field=models.ForeignKey(default=b'forum', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='percobaan.Jurnal_Ilmiah'),
        ),
        migrations.AddField(
            model_name='jurnal_authors_role',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.Role'),
        ),
        migrations.AddField(
            model_name='hibah_non_penelitian_authors_role',
            name='nama_kegiatan',
            field=models.ForeignKey(default=b'hibah_non_penelitian', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='percobaan.Hibah_Non_Penelitian_Kontrak_Kerja'),
        ),
        migrations.AddField(
            model_name='forum_authors_role',
            name='nama_kegiatan',
            field=models.ForeignKey(default=b'forum', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='percobaan.Forum_Ilmiah'),
        ),
        migrations.AddField(
            model_name='forum_authors_role',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.Role'),
        ),
        migrations.AddField(
            model_name='book_authors_role',
            name='judul_buku',
            field=models.ForeignKey(default=b'forum', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='percobaan.Buku_Teks_Ajar'),
        ),
        migrations.AddField(
            model_name='book_authors_role',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='percobaan.Role'),
        ),
    ]
